name: CI Pipeline

on:
  push:
    branches:
      - respaldo3_baseordenada2
  pull_request:

jobs:
  build:
    runs-on: self-hosted  # Tu runner en Windows

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias en raíz
        run: npm install

      - name: Instalar mysql2 (si lo necesitas)
        run: npm install mysql2

      - name: Preparar datos (db:setup desde main)
        run: npm run db:setup

      - name: Instalar dependencias en frontend
        run: npm --prefix frontend install

      - name: Compilar proyecto (desde frontend)
        run: npm --prefix frontend run build