name: CI Pipeline

on:
  push:
    branches:
      - respaldo3_baseordenada2
  pull_request:

jobs:
  build:
    runs-on: self-hosted  # Tu runner en Windows
    env:
    DB_HOST: ${{ 127.0.0.1 }}
    DB_PORT: ${{ 3306 }}
    DB_USER: ${{ root }}
    DB_PASSWORD: ${{ toki1801 }}
    DB_NAME: ${{ gofish }}
    RESEND_API_KEY: ${{ re_XbbCd682_9FCXbRraCLTeA4fuDs1inG82 }}
    FROM_EMAIL: ${{ gofishspa@resend.dev }}
    VERCEL_WEBHOOK_SECRET: ${{ gofish_vercel_webhook_secret_2024 }}
    NEXT_PUBLIC_BASE_URL: ${{ https://gofish-spa.vercel.app/ }}
    APP_URL: ${{ https://gofish-spa.vercel.app/ }}
    NEXTAUTH_URL: ${{ https://gofish-spa.vercel.app/ }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias en raíz
        run: npm install

      - name: Instalar mysql2 (si lo necesitas)
        run: npm install mysql2

      - name: Preparar datos (db:setup desde main)
        run: npm run db:setup

      - name: Instalar dependencias en frontend
        run: npm --prefix frontend install

      - name: Compilar proyecto (desde frontend)
        run: npm --prefix frontend run build