name: CI Pipeline

on:
  push:
    branches:
      - respaldo3_baseordenada2
  pull_request:

jobs:
  build:
    runs-on: self-hosted  # Usa tu runner instalado en Windows
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Preparar datos (db:setup)
        run: npm run db:setup

      - name: Compilar proyecto
        run: npm run build
      - name: Ejecutar pruebas
        run: npm test

